### ISSUE TITLE
Rename the developer docs

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1262]
It seems like people are being thrown off by the name "Getting Started". They feel like they shouldn't submit their documentation to be merged here because they're worried about it being out of scope.

**Comment by lukasmiddelberg** [comment]
What would you rename it to, then? I think "Getting started" is quite a good name for a page that actually gets you started. There should just be separate pages providing further reading, such as "An introduction to GStreamer", "How to use Contractor" or "Dealing with Notifications".

Squeezing all of this into one huge page of documentation would make it confusing and would probably put newcomers off because it would seem like a whole lot of work to actually start developing stuff.

**Comment by lewisgoddard** [comment]
@danrabbit I'd be interested in your thoughts about starting to break that document up a little bit.

I know we designed the page and navigation to be as sizable as we like, but at a certain point it does become a little daunting.

**Comment by danrabbit** [comment]
Yeah I'm just unsure what's the best way to break it up. It's written to be worked through linearly. Each section assumes the knowledge gained in the previous sections. I was almost thinking of some way to break it into courses or something. I'm not sure.

**Comment by lewisgoddard** [comment]
If we just want to ranem to "How to make an app" then this is bitesize, if we want to break it into courses then it definitely isn't. Until we have a course of action, I'm going to drop that label.

**Comment by danrabbit** [comment]
Closing since it's just called "Developer Guide" on docs now
