### ISSUE TITLE
Collect uncaught JS errors

### ISSUE THREAD

**Issue by emersion** [elementary/website#1330]
Send JS errors to analytics.

**Comment by lewisgoddard** [comment]
https://docs.newrelic.com/docs/browser/new-relic-browser/page-load-timing-resources/instrumentation-browser-monitoring

**Comment by lewisgoddard** [comment]
So it turns out browser monitoring with stack traces is quite expensive on New Relic.

https://sentry.io/pricing/ 
$29/mo for 28,800 events/day

https://sentry.io/platforms/
JavaScript, PHP, Node.

**Comment by eprozium** [comment]
> So it turns out browser monitoring with stack traces is quite expensive on New Relic.

Why  buy a service for such a basic functionality that can be done with a few lines of code and config?

Just collect the window onError event on every page (with the extra info you need) and POST it to a simple stateless Servlet(or other serverside solution) that will push it into a queue with persistence like Kafka or a NoSQL solution like RethinkDB or ElasticSearch directly. 

It might not look as shiny like the payed services, but it does the job and the otherwise unobserved bugs can be caught easily this way.

**Comment by btkostner** [comment]
@eprozium We would like not having to worry about another moving part / extra work on our side.

While we _could_ setup our own database and server to catch the errors, we would like to be able to extend this to all of our services (PHP, nodejs, and client side Javascript), and the man power it would take to write the code, and test it seems too much. With that said, we don't need to use a paid service. If you know of any good projects that are free, open source, or self hosted, let us know and we will take a look. We would just like to avoid reinventing the wheel.

**Comment by eprozium** [comment]
> We would like not having to worry about another moving part / extra work on our side.

This part is the single that everybody who has browser code (intranet or Internet) **should** really worry about because the browser: is the most fragile, one has the least control over it and it's constantly changing: again without one's control over it :).

> We would just like to avoid reinventing the wheel.

A few code lines is not reinventing the wheel, the same way putting a few log statements in your server code is not reinventing the wheel :).

>  If you know of any good projects ...

My experience with those is that for such a simple functionality, a DIY solution is quicker and faster: just to learn and integrate the stuff from others takes longer than to implement and deploy with Docker a minimal  JS Error Logging.

**Comment by lewisgoddard** [comment]
I'm sorry, but that's not going to allow for graphical stack traces that link into the code, nor will it be a "few code lines" to cover JS, PHP, and Node.

**Comment by btkostner** [comment]
This is now implemented and working. Closing issue.
