### ISSUE TITLE
Scrolling navigation isn't very responsible responsiveness.

### ISSUE THREAD

**Issue by rfoel** [elementary/website#1344]
One fact that bugs me a little is the fact that the navigation isn't responsive, unlike the rest of the website. We could give a little work there ;)

**Comment by lewisgoddard** [comment]
This is either a duplicate or a continuation of #275

**Comment by rfoel** [comment]
@lewisgoddard true thing, I checked them out. But it was over a year ago and I think a scroll isn't a good approach.

**Comment by lewisgoddard** [comment]
I'll ping design on this.

It's better than hamburger menus, since it exposes as much as possible by default, rather than nothing at all, but maybe people can't tell they can scroll.

**Comment by danrabbit** [comment]
haha cute title change ;p

I agree that there could be some more obvious affordance for the scrolling, but I do think that it exposes more links more quickly.

On a 4.7" phone (like maybe iPhone 6 which seems to be a popular size) you can see every link except "Get Involved" immediately. Even on a tiny phone like iPhone 5 or SE you'll still see the beginning of the developer link. So I think for the majority of people, this design exposes the most links immediately instead of hiding them behind something like a hamburger.

Perhaps it would be worth exploring some kind of overflow menu: appending items that are off-screen to a "..." menu item?

**Comment by cassidyjames** [comment]
Providing simple affordance such as a gradient to the bg color on the overflowed edges to hint at their scrollability could be a solution.

**Comment by rfoel** [comment]
@danrabbit on my Galaxy S6 though it cuts in 'De' from Developer, and the browser shows the scroll bar for 5 seconds before it disappears. The "..." would work I guess, better than nothing at all.

**Comment by seyDoggy** [comment]
Just putting this out there, what about having the more critical links remain visible (or replaced with more space effective icons) while hiding the less critical links in a hamburger?

**Comment by Xristodoulos99** [comment]
Can i try work on it? Either make it a dropmenu or have the media moved somewhere else when the device is small
