### ISSUE TITLE
Download dialog is bad

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1352]
Super helpful bug title I know. Okay here we go!

- [x] doesn't need an 'x' button since it has "Cancel"
- [x] 'Loki' is not a great button label. Should be an explicit action like "Download"
- [x] Buttons should be right aligned not center

Just check out this guy for reference: https://elementary.io/docs/human-interface-guidelines#dialogs

- [x] A good icon would be apps/48/ubiquity.svg

**Comment by asjadsyed** [comment]
I came to download 0.4 Loki, and got to the same download dialog. I wanted to download through bittorrent, and so I clicked on the button that both stood out and had a magnet link icon beside it. When I got the "where to save?" dialog in Firefox, I became confused. I was questioning, "Did I not just click the bittorrent icon?". I was expecting the "open in Deluge?" dialog instead.

Turns out that since I saw the magnet link icon on the button, I assumed the whole button was for bittorrent. I consequently assumed the button beside it was for HTTP, and so I never bothered to read it. 

I never thought that one button would have two different functions (because usually when designers put in dividers on buttons, they do so to put the text on one side and a helper icon on the other, but the whole button still has the same functionality). The fact that FOSS projects usually prioritize downloading through bittorrent instead of HTTP to lighten the load on their servers also confirmed the idea in my mind that elementary OS would suggest/prioritize bittorrent.

So, my suggestion on how to improve the download dialog is this:
1) there be two buttons, one titled "Download via HTTP" and the other "Download via BitTorrent".
2) each button should be physically-separated so they are not assumed to be doing the same thing
3) the HTTP button should get its own icon which complements the BitTorrent button's style (flat, white on light blue) (the icon doesn't need to do anything with HTTP specifically, a generic icon like [this](https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Applications-internet.svg/1024px-Applications-internet.svg.png) which represents the internet works well too)
4) the HTTP button should be the suggested action (with styling similar to the blue icon from [here](https://elementary.io/docs/human-interface-guidelines#dialogs) in the HIG), because users who have no idea about what either means shouldn't be confused and users who understand what each is and want to use bittorrent should be able to spot the magnet link icon.
