### ISSUE TITLE
align

### ISSUE THREAD

**Issue by gauthampkrishnan** [elementary/website#1478]
align the header button in center i would like to take control of the site i will make it superb i know css html php and sql

**Comment by btkostner** [comment]
The header link split is by design. We have an open issue about it's responsiveness at #1344.

As for control, this repository will always be under the elementary organization, but we do accept PRs from everyone. You can take a look at the [get-involved](https://elementary.io/get-involved) page on our website for more information about contributing to elementary, and our [CONTRIBUTING](https://github.com/elementary/website/blob/master/.github/CONTRIBUTING.md) file for specifics to this repository.
