### ISSUE TITLE
Transifex-to-Github translations sync

### ISSUE THREAD

**Issue by png2378** [elementary/website#1496]
For high-quality translations we need a tool for regular automatic translations update. Whenever you push something new to the website that has to be translated, even if the translation team works fast enough, the translation appears with a big delay of 2+ months, because the website team updates templates and translations relatively rarely, every 4-6 weeks. We could update templates automatically every day and import translations every week or every 2 weeks, for example. We could use this tool for our other projects in the future, as well as it may be helpful for other open source projects which uses Transifex.

**Comment by lewisgoddard** [comment]
I'd love to see translations removed from this repo and just automatically deployed when pushed.

**Comment by btkostner** [comment]
Something along this line of flow:

- Removed translations from repository
- Travis test includes pulling new translations and running tests
- When deployed, the server pulls new translations

Two things seem rather iffy with this:
- PRs could break due to translation errors (not code errors)
- Bad translations could be added between the time of testing and deploying, resulting in breaking pages.

**Comment by lewisgoddard** [comment]
Right, it puts a lot more control in the translators hands. Maybe an automatic pull-request then? Once a week?

**Comment by png2378** [comment]
As I said, it would be optimal to update templates every day and pull translations every week.

**Comment by danrabbit** [comment]
Going to close this since we do translations from weblate now
