### ISSUE TITLE
3 Ways to Explore" shows app names in wrong language

### ISSUE THREAD

**Issue by theel0ja** [elementary/website#1537]
### Expected behavior

"3 Ways to Explore" animation shows app names in local language

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/5832930/21717883/7b1474e6-d41c-11e6-980a-322011b30006.png)

### Steps to reproduce the behavior

1. Go to https://elementary.io/fi/
2. Go to **Kolme tapaa selata**
3. See English app names in animation

**Comment by png2378** [comment]
If we translate app names on local languages, content of the animation will be meaningless.

For this reason I use original English language in slingshot animation on Russian locale (including category names), perhaps it would be appropriate to exclude this part of translation templates.

**Comment by btkostner** [comment]
I'll give @png2378 final say if this is a problem that needs fixing or not.

**Comment by png2378** [comment]
@theel0ja if you translate app names to Finnish language, search results will not match `päi` search phrase. For example translation of Calendar name [looks like](https://translations.launchpad.net/maya/trunk/+pots/extra/fi/1/+translate) "Kalenteri" and this word doesn't include `päi`. The situation could be repeated in other languages. Eventually search results is nonsense and therefore I oppose your suggestion.

@btkostner I see two ways to solve this issue. After I discussed the issue with @leonardo-lemos, he suggested that we need to develop backend for correct search results in other languages (but I understand that the efforts is unjustified). Otherwise, I think will be better to completely eliminate translations from `slingshot` div on index page (including `dat` search pharse and category names) for unified style.

**Comment by lewisgoddard** [comment]
I don't think we should be doing this while our screenshots are not localized, it seems like a weird focus of effort, even if it might be easier to crowd-source.
