### ISSUE TITLE
Should elementary have a profile on LinkedIn?

### ISSUE THREAD

**Issue by vikaskyadav** [elementary/website#1568]
Why isn't there any linkedin profile for elemenetary.io ? It would gather more traction for elementaryOS.

**Comment by cassidyjames** [comment]
It would also mean someone posting to, maintaining, and responding to anything on LinkedIn. None of us use LinkedIn, so that would be a lot of extra work for something we aren't regularly using anyway. I'm going to close this as it's not strictly a website issue, but feel free to continue any discussion here.
