### ISSUE TITLE
New mirror needed in Vietnam?

### ISSUE THREAD

**Issue by karibuTW** [elementary/website#1617]
Hi there,

I am the mirror operator of mirror.freedif.org located in Vietnam (Ho Chi Minh City).
I have some spare bandwidth and space and would like to further contribute to your project.

Do you need a mirror in Vietnam (Can be used in the region)

Thanks

**Comment by lewisgoddard** [comment]
Hi there,

While we appreciate the offer, elementary run their system on five (previously six) distributed servers on [Digital Ocean](https://www.digitalocean.com/?refcode=eca8f5e3972c) with unlimited bandwidth that we discussed [when we left SourceForge](http://blog.elementary.io/post/121768724076/goodbye-sourceforge).

![Download Servers](https://cloud.githubusercontent.com/assets/831389/23096328/17b9210e-f612-11e6-836d-616a01478d05.png)

Since then we haven't really had any issues with throughput, there's plenty of spare resources for a release and we quite like having our own custom setup that we can monitor and manage quite effectively.
