### ISSUE TITLE
Don't accept payment less than US$ 1

### ISSUE THREAD

**Issue by acagastya** [elementary/website#1651]
### Expected behavior
As @btkostner mentioned for bug #1649 "This [payment window not showing for amount less than 1 dollar] is intended behavior. It's not cost effective to process payments under $1", the Custom input should not accept values less than US$ 1.

### Actual behavior
Custom textbox accepts payment less than one dollar but payment window does not open.

### Steps to reproduce the behavior

Refer issue #1649

**Comment by lewisgoddard** [comment]
When someone types `0.1`, what would you expect to happen, given that we accept both $0 and $1

**Comment by acagastya** [comment]
There are multiple ways to tackle this issue. One way, we can provide a button to "download without any donation". We can also have a tooltip which tells the users to pay at least a dollar if they want to donate. Else, just like how $1.001 is not a valid input, 0.001 to 0.999 should be invalid.

**Comment by btkostner** [comment]
I personally put my vote to the last solution. 0.99 should show just like other invalid values.

**Comment by cassidyjames** [comment]
Keep in mind payments are not donations. elementary is not a non-profit; we provide elementary OS for a pay-what-you-want price that happens to include $0.

**Comment by lewisgoddard** [comment]
The only issue with @btkostner comment is that invalid items force it to default back to the previously selected amount (usually $10). This would need an exception for otherwise valid amounts below $1.

**Comment by acagastya** [comment]
Why is the default not set to zero?

**Comment by danrabbit** [comment]
The default isn't 0 because elementary OS is not free to make. This is how we stay in business.

**Comment by acagastya** [comment]
True. It is not free to make. Users can choose to pay what they want to. But this does not follow the ideology of free and open source softwares.

**Comment by acagastya** [comment]
But I don't understand, why users can't pay US$ 0.99?

**Comment by danrabbit** [comment]
This is a common misconception. Please see the FSF's notes on selling open source software: https://www.gnu.org/philosophy/selling.en.html

It's not free for us to processing credit card transactions either. We have to pay out a portion of the transaction to a credit card processor. Below $1 it starts to not make sense to process transactions because it costs us more to process than we make on the sale

**Comment by acagastya** [comment]
I did not say that one can not charge money for FOSS. Free software is free in terms of availability of source code, modification and redistribution. But when the user has an option for zero dollars, the default set to a non-zero does not seem quite right. 

But in any case, numbers between zero and one, excluding them should be in red colour (just like how 1.999 will be) so that users will know it is not a correct input.

**Comment by tehp** [comment]
@acagastya I disagree.
While it is possible to obtain for free, it is still a business and must still show possible buyers that paying for the software is an option. 

I agree that numbers like $0.99 USD should not be red though.

**Comment by acagastya** [comment]
$5, $10 and $25 buttons are visible for users to pay. "Pay What You Want" is also mentioned there. So possible buyers can see that paying is an option. 

If 0.99 is not an acceptable value, why not to show it in red?

**Comment by cassidyjames** [comment]
The difference between `0.99` and `1.999` is subtle, but important: 

1. We just round anything < $1 down and let the user proceed. 
2. With `1.999`, it is not a valid amount and we do not accept it as an input, so it's now in an error state and re-selects the default amount.

Since these two behaviors are different states with different results, it makes sense that they are treated differently. It's not an _error_ to round `0.99` down, so we don't need to mark it in red.

**Comment by acagastya** [comment]
It is you who round anything less than a dollar to zero, but when someone tried to pay, and enters 0.99 in the textbox, he/she thinks this is probably an error because it should work. Besides, especially, citizens of the US are used to 99. $99 iPhone, 99 cents songs, $3.99 iTunes movie rental, and 99 problems.
