### ISSUE TITLE
The code of coduct refers to IRC

### ISSUE THREAD

**Issue by tintou** [elementary/website#1668]
https://elementary.io/code-of-conduct
It refers to IRC when we don't actually use it anymore

**Comment by lewisgoddard** [comment]
See related: #1051

**Comment by cassidyjames** [comment]
Yeah there are a few things out of date, like referring to our wbsite which no longer has user-submitted content or accounts. I'd change:

# Community Guidelines
> anytime you’re involved with the community, be it on the elementary website, in an official IRC room, in person, or elsewhere.

to

> anytime you’re involved with the community, be it in Slack, on GitHub, on an elementary community site, in person, or anywhere else.

# IV. Helpful Discussion
> If participating in a developer-oriented discussion such as a mailing list or developer IRC channel,

to 

> If participating in a developer-oriented discussion such as an issue tracker, pull request, mailing list, IRC, or Slack,

(since this implies being involved in other community IRC channels, i.e. #gnome-hackers or whatever)

# Consequences

> alter or remove any content you’ve posted; deactivate your account on the website; kick you out of an IRC channel; ban you from the site, IRC channels, or related services; or otherwise prevent you from interacting with the community.

to

> alter or remove any content you’ve posted; deactivate or ban your account on third-party sites; deactivate your account in Slack; or otherwise prevent you from interacting with the community.
