### ISSUE TITLE
Terminal is interactive

### ISSUE THREAD

**Issue by danrabbit** [elementary/website#1671]
Something has gone awry. The Terminal animation is not supposed to accept input o.O

**Comment by btkostner** [comment]
Is it really a bug?

**Comment by lewisgoddard** [comment]
I think this was by design, you can use certain commands. In addition to the commands used to build the example output, you can:

- clear
- exit
- whoami
- USER=
- rm -rf  (appears broken)
- cd
- echo

See [_scripts/widgets/pantheon/terminal.js](https://github.com/elementary/website/blob/master/_scripts/widgets/pantheon/terminal.js)

**Comment by danrabbit** [comment]
It's janky and broken. As an animation it's great. But trying to embed an interactive Terminal is just going to be a poor representation of the actual app

**Comment by lewisgoddard** [comment]
Yeah, I think that's meant to be a thing only nerds will try, a neat easter egg.

**Comment by danrabbit** [comment]
It's a broken Easter egg

**Comment by lewisgoddard** [comment]
So do we want to kill the easter egg, or fix it?

**Comment by btkostner** [comment]
Might as well kill it now :rabbit: :gun:

**Comment by okitoxd** [comment]
I'm starting to support Elementary, let me try to solve it. Let's kill the Easter Egg

**Comment by okitoxd** [comment]
#1705
