### ISSUE TITLE
Let's translate "Use PayPal"

### ISSUE THREAD

**Issue by png2378** [elementary/website#1685]
For some reason, "Use PayPal" string on get-involved page is not available for translation.

![](http://storage8.static.itmages.ru/i/17/0501/h_1493630357_3604411_944ec0e966.png)

**Comment by brunocamarggo** [comment]
The reason is because the string "Use PayPal" is an attribute `value` of an `input` tag. At the moment,  in an `input` tag, just the attribute `placeholder` can be translated.

To solve this problem, we could just replace the line 297 of the file` L10n.php` adding the attribute `value` to be translate:

` 'input' => array('placeholder', 'value')`

Finally, the file `get-involved.json` need be changed, adding the translation for "Use PayPal".

I could change the file `L10n.php`, but I don't know how to change `get-involved.json` in [Weblate](https://l10n.elementary.io/projects/website/get-involved).

**Comment by lewisgoddard** [comment]
Those JSON files are automatically generated, you'd need to patch the generator to allow for placeholders and values too.

**Comment by png2378** [comment]
Perhaps we also need to include `title` attribute in `L10n.php`. 

Because I see this string on get-involved page:
`title="PayPal - The safer, easier way to pay online!"`

**Comment by NathanBnm** [comment]
> The reason is because the string "Use PayPal" is an attribute `value` of an `input` tag. At the moment, in an `input` tag, just the attribute `placeholder` can be translated.
> 
> To solve this problem, we could just replace the line 297 of the file` L10n.php` adding the attribute `value` to be translate:
> 
> ` 'input' => array('placeholder', 'value')`
> 
> Finally, the file `get-involved.json` need be changed, adding the translation for "Use PayPal".
> 
> I could change the file `L10n.php`, but I don't know how to change `get-involved.json` in [Weblate](https://l10n.elementary.io/projects/website/get-involved).

I have made these changes in a pull request, hope it will be accepted #2145

**Comment by NathanBnm** [comment]
> Perhaps we also need to include `title` attribute in `L10n.php`.
> 
> Because I see this string on get-involved page:
> `title="PayPal - The safer, easier way to pay online!"`

If it's working with the `value` attribute, we'll be able to add the `title` attribute too :+1:

**Comment by NathanBnm** [comment]
@btkostner can you help to find out why this button is still untranslated after I have made the required changes ? (See #2145 )

**Comment by btkostner** [comment]
@NathanBnm It should. It's in weblate: https://l10n.elementary.io/translate/website/get-involved/es/?checksum=9271ead95a8ebdfd

**Comment by NathanBnm** [comment]
You're right, so it's just the page which hasn't been updated for the moment I mean.

I am going to add the input title attribute too.
