### ISSUE TITLE
Some docs lost translations after moving to Weblate

### ISSUE THREAD

**Issue by png2378** [elementary/website#1758]
After moving to Weblate we lost translations of docs-installation and docs-learning-the-basics.

**Comment by btkostner** [comment]
There was [a PR](https://github.com/elementary/website/pull/1751) a bit ago that pulled in a bunch of the translations from before weblate again. Otherwise, all the strings that are missing (should have been) duplicates or untranslated strings.

If they are still missing, could you please pick out a string from the past so I can test it with the latest migration scripts and see what is going wrong.

**Comment by png2378** [comment]
@btkostner, indeed, I see all translated strings [here](https://github.com/elementary/website/blob/master/_lang/ru/docs/installation.json). But for some reason [Weblate](https://l10n.elementary.io/projects/website/docs-installation/ru/) UI says they are not translated.

**Comment by btkostner** [comment]
Very odd. It's probably a parsing error on weblate (possibly encoding issue?). I'll take a look at it tonight.

**Comment by png2378** [comment]
I doubt that this is encoding issue, because I see [same situation](https://l10n.elementary.io/projects/website/docs-installation/) with other languages.

**Comment by btkostner** [comment]
@png2378 can you check now?

**Comment by png2378** [comment]
@btkostner, fixed now, thanks!
