### ISSUE TITLE
Some translatable strings missed

### ISSUE THREAD

**Issue by png2378** [elementary/website#1760]
After commit https://github.com/elementary/website/commit/922c1406fd24dca0027b2f8a3505c268d9a2a518 some translatable strings are lost.

For example it is `Community & Collaborators` and `elementary would not exist without the involvement of dedicated community members and collaborators from other free and open source projects` on the Team page.

![](http://storage1.static.itmages.ru/i/17/0620/h_1497982912_6580072_dcade0b6c0.png)

_(I agree that time zones can be deleted)_

**Comment by btkostner** [comment]
This was caused by us moving to automating the text extraction. The weblate instance has no API keys, so anything that was outputed from an API, or outputted _because_ of an API will no longer get put in the translation files.

For the `team.php` page specifically, we just had to move some `if` statements around.

**Comment by png2378** [comment]
@btkostner I apologize for importunity, but issue has not been fully fixed (strings didn't appear in Weblate).

**Comment by btkostner** [comment]
The website side of things is working, just looks like weblate isn't picking up the new strings. Going to re-open until I figure out what's going wrong on weblate's side.

**Comment by png2378** [comment]
Fixed now, thanks.
