### ISSUE TITLE
Still references to "Scratch" editor. Isn't it "Code" now?

### ISSUE THREAD

**Issue by megatux** [elementary/website#2077]
### Expected behavior

Use the new app name

### Actual behavior

"Scratch" name used in app. list and in its own app. section.

Did a [search](https://github.com/elementary/website/search?q=scratch&type=Code) and still exists

    292 code results in elementary/website

### System information

lang: es_ar

**Comment by megatux** [comment]
Maybe it's on purpose? I still can find the app in the app menu writing "scratch"

**Comment by megatux** [comment]
I checked _juno_ branch and still see references to "Scratch"

**Comment by danrabbit** [comment]
References to Scratch should be changed when [this branch](https://github.com/elementary/website/pull/2057) lands upon the release of Juno. If you see instances of Scratch in that branch, please leave comments there.

Otherwise this report is technically invalid since Juno (and Code) haven't yet been released. Scratch is accurate for the current Loki release.
