### ISSUE TITLE
Make 64-bit requirement more obvious

### ISSUE THREAD

**Issue by cassidyjames** [elementary/website#2183]
We get occasional support emails about people trying to install on 32-bit computers. We should make it more obvious that it's 64-bit only, whether that's from the homepage or just more obvious on the installation instructions.

**Comment by ejerez** [comment]
![image](https://user-images.githubusercontent.com/28111727/57880817-90f10f00-77d4-11e9-9aa5-d8ee55a2b4f8.png)

Could this be a start? Or somewhere else more appropriate?

**Comment by cassidyjames** [comment]
That's starting to get a little more cluttered there, but it could possible work. Thoughts, @danrabbit?

**Comment by ejerez** [comment]
![Screenshot from 2019-05-16 16 47 22](https://user-images.githubusercontent.com/28111727/57894079-6154fd80-77fa-11e9-9ad3-387a040cc4cb.png)
@cassidyjames Since we are already saying that Elementary is a replacement for Windows and Mac, I thought it might be redundant to repeat the same information. Maybe this can work?

**Comment by lewisgoddard** [comment]
What about two lines?

---

**Purchase elementary OS**
elementary OS 5.0 Juno
1.48 GB | 64-bit

**Comment by cassidyjames** [comment]
@lewisgoddard 

![Make it so!](https://media3.giphy.com/media/bKnEnd65zqxfq/giphy.gif?cid=790b76115ce2dea72e32434445716907&rid=giphy.gif)

**Comment by ejerez** [comment]
@lewisgoddard @cassidyjames Just sent a pull request. It's my first commit ever to open source. Thank you guys for delivering an amazing piece of work. Best OS ever!
