### ISSUE TITLE
Epiphany crashes on elementary.io

### ISSUE THREAD

**Issue by aral** [elementary/website#2743]
## What happens

Epiphany crashes while browsing the elementary.io home page.

## What should happen

Nothing extraordinary.

## What actually happens

![Screenshot from 2020-12-09 10-54-15@2x](https://user-images.githubusercontent.com/41798/101622363-dc9a8780-3a0e-11eb-87a7-e232410c83d3.png)

The browser tab crashes.

## Steps to Reproduce

1. Open https://elementary.io in Epiphany.
2. Scroll down and around a bit.

## Platform Information

```
OS: elementary OS 5.1.7 Hera x86_64 
Host: LabTop Mk IV 
Kernel: 5.4.0-56-generic 
Uptime: 23 hours, 52 mins 
Packages: 1719 
Shell: zsh 5.4.2 
Resolution: 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 4672MiB / 15883MiB 
```

**Comment by aral** [comment]
Unless I’m mistaken, this fixes the symptom, not the actual bug in Epiphany. Do you know if the actual bug is being tracked anywhere else?

**Comment by cassidyjames** [comment]
@aral we don't make modifications to the rendering of Epiphany, so that would need to be reported upstream at https://gitlab.gnome.org/GNOME/epiphany/ or possibly even WebKit itself.

The hard part is figuring out exactly what was happening to cause a tab crash, tracing it, etc. which unfortunately I don't have knowledge or experience in. But again, considering we weren't seeing tons of crashes across the web, this was the most direct way to fix it for our users. I'd still be interested in having someone track the crash down if they have the time, though.
