### ISSUE TITLE
Website - Download

### ISSUE THREAD

**Issue by itexpert120** [elementary/website#2747]
## Problem

The elementary OS webpage defaults to 20$ on download.
This may lead to people thinking that paying is must for downloading this OS.

## Proposal

Either default to 0$ or add a 0$ option on the pay what you want dialoge to avoid this confusion.

## Prior Art

Not sure if I've seen others use this Pay what you want scheme before lol but having a 0$ or default "Free" option will make it easier for new users.

**Comment by cassidyjames** [comment]
elementary OS is considered a paid product. We've covered this at length in the past, notably over six years ago: https://blog.elementary.io/payments/

In the time since then, we've had consistently strong growth from release to release with the number of downloads—both free and paid. The proportion of paid downloads has also increased, but is still in the single-digit percentages. This proves to us the current approach is successful and sustainable, and we are not turning away significant numbers of users. You can examine the stats yourself on our public dashboard: https://plausible.io/elementary.io

We do expect to revisit the exact design with a reworking of the homepage some time around or after the OS 6 release, but that will be part of a larger project and won't necessarily address this issue directly.
