### ISSUE TITLE
Developer Website needs to change elementary version

### ISSUE THREAD

**Issue by M4rk3h** [elementary/website#2831]
## Problem

On the [Developer](https://developer.elementary.io/) page, the elementary os version at the bottom is still referencing 5.1. 

> Download elementary OS 5.1 Hera

## Proposal

Changing it to reflect the new version (6 at the time of writing this) with a link to the release notes below it,

## Prior Art

I did try to go through the code and create a pull request, but my web dev experience is in basic html, css, js and using the framework bootstrap - nothing to do with nodejs etc.

**Comment by pedropaulosuzuki** [comment]
Yes, I just noticed that and was about to open an issue about it. 

Link: <https://developer.elementary.io/>.
Screenshot: 
![image](https://user-images.githubusercontent.com/32345702/133109070-e86e5245-ac33-4854-b307-daac23c8094e.png)

**Comment by pedropaulosuzuki** [comment]
I'd be glad to open an issue to quickly fix that, but I cannot find the correct file. The best I could find is [this file](https://github.com/elementary/website/blob/master/developer.php), but it is only a redirect. Does anyone know where can I find the actual HTML or Markdown text in order to edit it? I'd be glad to open an issue and fix it, but I don't know where this text is coming from.

**Comment by StylusEater** [comment]
@pedropaulosuzuki and @M4rk3h this issues looks fixed. Please confirm.

**Comment by pedropaulosuzuki** [comment]
> @pedropaulosuzuki and @M4rk3h this issues looks fixed. Please confirm.

Yeah, seems fixed to me!

**Comment by pedropaulosuzuki** [comment]
BTW, is it worth it to have that page in the Houston repository? Wouldn't it be more convenient to have it on this repo instead? Like I tried looking for it on a lot of repos and couldn't find it, I'd never guess it was in the Houston repo hehe

**Comment by M4rk3h** [comment]
It's looking good - thanks for this.
