### ISSUE TITLE
Mission statement on website is (likely unintentionally) misleading

### ISSUE THREAD

**Issue by HollowedEmpire** [elementary/website#2894]
### What Happened?

Hello!

While this may seem nitpick initially, this minor change in wording can help resolve (what I'm sure is unintentional/accidentally) misleading information on the use of elementaryOS.

On the website, the opening mission statement is as follows: "The thoughtful, capable, and ethical _replacement_ for Windows and macOS". This is nice and all but it is, apparently, incorrect as confirmed by contributors working on elementaryOS.

According to both Files maintainer jeremypw, and Files contributor Marukesu, they have confirmed with me multiple times that elementaryOS should absolutely _not_ be considered a replacement to either Windows or Mac (or even other Linux distros) and instead is actually an "alternative". They had confirmed it was a mistake on my part for believing that it could be a replacement OS, of which I got that contradicting information directly from elementaryOS's website.

As such, simply changing the wording to "The thoughtful, capable, and ethical _alternative_ for Windows and macOS" would be more accurate and less misleading. I agree with them on their word choice, and it would have me less likely to believe I could use it as a replacement OS and would instead use it alongside another.

Just want to help pass that along so nobody else is mistaken by it.

Thanks!

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by cassidyjames** [comment]
@HollowedEmpire eh, we used to say "alternative to" but after talking with people out in the world (like at SCALE and just social media in general), we decided to be more assertive about elementary OS being a replacement for other OSes. Just like a new iPhone could be a replacement for an old Android phone or a new Tesla can be a replacement for an old Honda, elementary OS absolutely is a replacement for your old OS—it literally replaces the OS on your machine by default.

However, that doesn't mean it's designed to work exactly like what it's replacing. You wouldn't expect a new iPhone to work just like an old Android phone, or a new Tesla to work just like an old Honda. If you're expecting elementary OS to be a _copy_ or _reimplementation_ of what it's replacing, you're gonna have a bad time.

Since this wording was intentional (and has helped people better understand what elementary OS is!), this issue can be closed.

**Comment by HollowedEmpire** [comment]
Hmm, well, you may want to talk to your fellow teammates about that if what you believe you are saying is true. What you wrote contradicts what they had explained to me. Also, your examples about elementary replacing another OS weren't really on target either. Perhaps it wasn't clear enough, so I'll work with your examples to help clarify:

What I'm saying is I'd expect a new phone to make calls and texts like an old phone. Just as I'd expect a new car to have gas and break pedals operate in the same manner as the old car. Basic core things are what I'm taking about. What I'm _not_ talking about the two to share _exact_ specific workings, menus, presentation, graphics, or any of that. This is what jeremypw and Marukesu explained to me; that I shouldn't expect elementaryOS to replace another OS at a *core* level. If elementary was a new phone, I shouldn't expect it to make calls or texts like the old phone. Hence why saying it is a replacement OS was confusing since they explained it isn't at a fundamental level.

So intentional wording has not made it clearer at all. At the risk of pointing out the obvious, had the wording been clear I wouldn't have submitted this as a problem in the first place. Either that, or perhaps the development team just doesn't have a clear idea of what elementary OS is itself. It might be a good idea to get the team together so all of you can provide the same information to users.
