### ISSUE TITLE
Add stripe to funding section of get involved

### ISSUE THREAD

**Issue by danirabbit** [elementary/website#624]
Because it makes sense to offer credit and debit card there too, I think

**Comment by danrabbit** [comment]
Commenting to note that Stripe also handles BitCoin and Alipay now

**Comment by lewisgoddard** [comment]
We just redesigned the funding section last month, and we didn't add this then.
https://github.com/elementary/mvp/blame/master/get-involved.php
https://elementary.io/get-involved#funding

**Comment by lewisgoddard** [comment]
Would we like Stripe added underneath PayPal?

**Comment by danrabbit** [comment]
Yes, I think so.

If we could set up subscriptions with Stripe I think that several of us came to the conclusion that it should replace Patreon.

**Comment by danrabbit** [comment]
![screenshot from 2016-11-17 11 46 22](https://cloud.githubusercontent.com/assets/7277719/20405434/e30bfc58-acbd-11e6-88a0-16572d50d968.png)

Just gonna leave this here. An idea for driving engagement and providing a little bit of budget transparency.

Each colored section would have a tooltip that explains what it is. They represent different sources of income like downloads, the store, and pledges from this page.

The total here represents our monthly budget and the progressbar resets at the beginning of each month. This is because we want to raise an amount of money that keeps us in the black each month and not have to rely on a big release month to carry us through the year.

I've chosen to use percentages here instead of real dollars for a couple reasons: Our employees salaries should be their own private information to choose to share or not. We do our best to maintain a frugal budget, but humans are not cheap and I don't want people trying to guess what our employees make (trust me it's embarrassing). I want to represent how much each revenue stream contributes to the total, particularly how important downloads are to our monthly budget and how much we have left to go each month. These comparisons don't require showing real dollar amounts.

I would like to make use of the subscription feature of Stripe and try to get people to use this instead of Bountysource and Patreon. We get a bigger cut of the pledge when there are less hands in the cookie jar.

**Comment by lewisgoddard** [comment]
Partially blocked by #1530

**Comment by danirabbit** [comment]
Closing because Stripe doesn't allow crowdfunding
